Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
  
    config.vm.define "nodom" do |nodom|
      nodom.vm.network "private_network", ip: "192.168.30.3", netmask: "255.255.255.0"
      nodom.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
      nodom.vm.provision "shell", path: "pythonins.sh"
    end
  
    config.vm.define "nodo1" do |nodo1|
      nodo1.vm.network "private_network", ip: "192.168.30.4", netmask: "255.255.255.0"
      nodo1.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  
    config.vm.define "nodo2" do |nodo2|
      nodo2.vm.network "private_network", ip: "192.168.30.5", netmask: "255.255.255.0"
      nodo2.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  
    config.vm.define "nodo3" do |nodo3|
      nodo3.vm.network "private_network", ip: "192.168.30.6", netmask: "255.255.255.0"
      nodo3.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  end