Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

#SETTINGS FOR THE MASTER NODE---------------------------------------------------------------
    config.vm.define "masternode" do |masternode|
      masternode.vm.network "private_network", ip: "192.168.30.3", netmask: "255.255.255.0"
      masternode.vm.provider "virtualbox" do |vb|
        vb.name = "nodemasteransible"
        vb.memory = "4096"
        vb.cpus = 2
      end
      masternode.vm.provision "shell", path: "pythonins.sh"
    end

#SETTINGS FOR THE VMs (change any parameter as you want)-----------------------------------  
    config.vm.define "node1" do |node1|
      node1.vm.network "private_network", ip: "192.168.30.4", netmask: "255.255.255.0"
      node1.vm.provider "virtualbox" do |vb|
        vb.name = "node1ansible"
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  
    config.vm.define "node2" do |node2|
      node2.vm.network "private_network", ip: "192.168.30.5", netmask: "255.255.255.0"
      node2.vm.provider "virtualbox" do |vb|
        vb.name = "node2ansible"
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  
    config.vm.define "node3" do |node3|
      node3.vm.network "private_network", ip: "192.168.30.6", netmask: "255.255.255.0"
      node3.vm.provider "virtualbox" do |vb|
        vb.name = "node3ansible"
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  end