Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.define "phpenvironment" do |php|
        php.vm.synced_folder "./phpdevapache/", "/var/www/html/"
        php.vm.hostname = "phpdevpablo"
        php.vm.provider "virtualbox" do |vb|
            vb.name = "phpdev"
            vb.memory = "2048"
            vb.cpus = 2
        end
        php.vm.provision "shell", path: "setup.sh"
    end
  end