Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.define "phpenvironment" do |php|
        php.vm.network "private_network", ip: "192.168.30.33", netmask: "255.255.255.0"
        php.vm.synced_folder "./phpdevapache/", "/var/www/html/" #CHANGE THE ROUTE IF YOU WANT (1ST ROUTE ONLY)
        php.vm.hostname = "phpdevpablo"
        php.vm.provider "virtualbox" do |vb|
            vb.name = "phpdev"
            vb.memory = "2048"
            vb.cpus = 2
        end
        php.vm.provision "shell", path: "./scripts/setup.sh"
    end
  end