Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.network "private_network", ip: "192.168.30.33", netmask: "255.255.255.0"
        wordpress.vm.synced_folder "./linkwordpress/", "/var/www/wppablo.net/" #CHANGE THE ROUTE IF YOU WANT (1ST ROUTE ONLY)
        wordpress.vm.hostname = "wordpress"
        wordpress.vm.provider "virtualbox" do |vb|
            vb.name = "wordpress"
            vb.memory = "2048"
            vb.cpus = 2
        end
        wordpress.vm.provision "shell", path: "./scripts/setup.sh"
    end
  end