Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64" # box used ubuntu 18.04
  config.vm.box_version = "20230607.0.5" # version box
  config.vm.network "public_network" # bridge adapter
  config.vm.define "serverweb" # name of the machine vagrant
    
  config.vm.provider "virtualbox" do |vb| # vb as hypervisor
    vb.name ="serverweb"
    vb.gui = true #gui launched
    
    vb.memory = "4096" # Customize the amount of memory on the VM:
    vb.cpus = 4 # number of cores used
end

config.vm.provision "shell", inline: <<SHELL # script used at the start
  apt-get update && apt-get upgrade 
  apt-get install apache2 git -y
SHELL

end
  
