Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20230607.0.5"
  config.vm.network "public_network", ip: "172.19.200.67"
  config.vm.define "serverweb"
  #config.disksize.size = "50GB"# size of the disk, requires plugin || vagrant plugin install vagrant-disksize || 

  config.vm.provider "virtualbox" do |vb| # vb as hypervisor
    vb.name ="serverweb"
    vb.gui = true 
    vb.memory = "4096"
    vb.cpus = 4
end
  config.vm.provision "shell", path: "initialconfig.sh"
  config.vm.provision "shell", path: "guestadditions.sh"
  config.vm.provision "shell", path: "services.sh"
  config.vm.provision "shell", inline: <<SHELL
  echo -e "All instalations finished."
SHELL
end
  
