Vagrant.configure("2") do |config|
  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.box = "ubuntu/bionic64"
    dhcp.vm.box_version = "20230124.0.0"
    dhcp.vm.network "public_network", ip: "172.19.200.67", netmask: "255.255.0.0", gateway: "172.19.0.254" #enp0s8
    dhcp.vm.network "private_network", ip:"10.33.200.1"
    dhcp.vm.provider "virtualbox" do |vb| # vb as hypervisor
      vb.name ="serverdhcp"
      vb.gui = true 
      vb.memory = "4096"
      vb.cpus = 4
    dhcp.vm.provision "shell", path: "initialconfig.sh", run: 'always'
    #dhcp.vm.provision "shell", path: "guestadditions.sh"
    dhcp.vm.provision "shell", path: "dhcpserver.sh"
    dhcp.vm.provision "shell", inline: <<SHELL
    sudo sysctl -p
    echo -e "All the steps for the dhcp server has finished."
    sudo reboot
SHELL
  end
end

config.vm.define "web" do |web|
  web.vm.box = "ubuntu/bionic64"
  web.vm.box_version = "20230124.0.0"
  web.vm.network "public_network", ip: "172.19.200.69", netmask: "255.255.0.0", gateway: "172.19.0.254" 
  web.vm.provider "virtualbox" do |vb| # vb as hypervisor
    vb.name ="web"
    vb.gui = true 
    vb.memory = "4096"
    vb.cpus = 4
  web.vm.provision "shell", path: "services.sh"
end
end
end
